// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    'IconParkOutline:docFail': typeof import('~icons/icon-park-outline/doc-fail')['default']
    'Mdi:cardsHeart': typeof import('~icons/mdi/cards-heart')['default']
    'MdiLight:loading': typeof import('~icons/mdi-light/loading')['default']
    'MdiLight:noteText': typeof import('virtual:vite-icons/mdi-light/note-text')['default']
  }
}

export {}
